### ISSUE TITLE
rhealpix is not supported

### ISSUE THREAD

**Issue by RuixiangLiuWHU** [locationtech/proj4j#109]
crsFactory.createFromParameters("rHEALPix", "+proj=healpix +ellps=WGS84")
Exception in thread "main" org.locationtech.proj4j.InvalidValueException: Unknown projection: healpix
	at org.locationtech.proj4j.parser.Proj4Parser.parseProjection(Proj4Parser.java:74)
	at org.locationtech.proj4j.parser.Proj4Parser.parse(Proj4Parser.java:58)
	at org.locationtech.proj4j.CRSFactory.createFromParameters(CRSFactory.java:127)
	at org.locationtech.proj4j.CRSFactory.createFromParameters(CRSFactory.java:106)

**Comment by pomadchin** [comment]
hi @RuixiangLiuWHU, yes we don't support it, a nice feature request!
